[phases.setup]
# Bun v1.1.31
nixPkgsArchive = "c29012c10c2a8d2ad65702f560c77cc7004a1cf9"
nixPkgs = ['...', "bun"]

[phases.install]
cmds = ["bun install --production"]

[phases.build]
cmds = [
  "bun build ./apps/bot/src/bot.ts --compile --minify --sourcemap --outfile ./apps/bot/dist/bot",
]

[start]
cmd = "./apps/bot/dist/bot"
